export const sydney = {
  "KT19 9UR": [
    "78 Chessington Road, Epsom, Surrey, KT19 9UR",
    "78a Chessington Road, Epsom, Surrey, KT19 9UR",
    "80 Chessington Road, Epsom, Surrey, KT19 9UR",
    "82 Chessington Road, Epsom, Surrey, KT19 9UR",
    "84 Chessington Road, Epsom, Surrey, KT19 9UR",
    "84A Chessington Road, Epsom, Surrey, KT19 9UR",
    "86 Chessington Road, Epsom, Surrey, KT19 9UR",
    "88 Chessington Road, Epsom, Surrey, KT19 9UR",
    "88a Chessington Road, Epsom, Surrey, KT19 9UR",
    "88b Chessington Road, Epsom, Surrey, KT19 9UR",
    "90 Chessington Road, Epsom, Surrey, KT19 9UR",
    "90a Chessington Road, Epsom, Surrey, KT19 9UR",
    "92 Chessington Road, Epsom, Surrey, KT19 9UR",
    "92a Chessington Road, Epsom, Surrey, KT19 9UR",
    "92B Chessington Road, Epsom, Surrey, KT19 9UR",
    "94 Chessington Road, Epsom, Surrey, KT19 9UR",
    "94a Chessington Road, Epsom, Surrey, KT19 9UR",
    "94B Chessington Road, Epsom, Surrey, KT19 9UR",
    "96 Chessington Road, Epsom, Surrey, KT19 9UR",
    "96a Chessington Road, Epsom, Surrey, KT19 9UR",
    "98 Chessington Road, Epsom, Surrey, KT19 9UR",
    "98a Chessington Road, Epsom, Surrey, KT19 9UR",
    "100 Chessington Road, Epsom, Surrey, KT19 9UR",
    "100a Chessington Road, Epsom, Surrey, KT19 9UR",
    "102 Chessington Road, Epsom, Surrey, KT19 9UR",
    "102a Chessington Road, Epsom, Surrey, KT19 9UR",
    "104 Chessington Road, Epsom, Surrey, KT19 9UR",
    "104a Chessington Road, Epsom, Surrey, KT19 9UR",
    "106a Chessington Road, Epsom, Surrey, KT19 9UR",
    "108 Chessington Road, Epsom, Surrey, KT19 9UR",
    "108a Chessington Road, Epsom, Surrey, KT19 9UR",
    "108b Chessington Road, Epsom, Surrey, KT19 9UR",
    "Akbaba Decoration Plumbing & Painting Ltd, 88A Chessington Road, Epsom, Surrey, KT19 9UR",
    "Ballards Convenience Ltd, 78 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Ballards Newsagents, West Ewell, Epsom, Surrey, KT19 9UR",
    "Celticpharm Ltd, 96 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Circle Pizza, 88 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Ewell Barbers Ltd, 104 Chessington Road, Epsom, Surrey, KT19 9UR",
    "First Floor Maisonette, 106A Chessington Road, Epsom, Surrey, KT19 9UR",
    "Flat 1, 92 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Flat A, 92 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Flat A, 94 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Flat B, 92 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Flat B, 94 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Go Sing Pang Limited, 86 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Go Sing, West Ewell, Epsom, Surrey, KT19 9UR",
    "Haohua Ltd, 86 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Istanbul Kebab, West Ewell, Epsom, Surrey, KT19 9UR",
    "Joanna Beauty Ltd, 106 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Kokaraddi Pillayar Store Ltd, 78 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Mezmar Ltd, 88 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Miles Pharmacy, West Ewell, Epsom, Surrey, KT19 9UR",
    "Montello Estates Ltd, 96A Chessington Road, Epsom, Surrey, KT19 9UR",
    "Mzlm Ltd, 88 Chessington Road, Epsom, Surrey, KT19 9UR",
    "New Go Sing Ltd, 86 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Pastry Palace Ltd, 88A Chessington Road, Epsom, Surrey, KT19 9UR",
    "Rico Coffee, West Ewell, Epsom, Surrey, KT19 9UR",
    "Sage Boutique Ltd, 102 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Sunshine Cafe (S.G) Ltd, 92 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Sunshine Cafe, West Ewell, Epsom, Surrey, KT19 9UR",
    "Susies Diner, 92 Chessington Road, Epsom, Surrey, KT19 9UR",
    "T.M Best Ltd, 92 Chessington Road, Epsom, Surrey, KT19 9UR",
    "The Co-Operative Food, West Ewell, Epsom, Surrey, KT19 9UR",
    "Unit 4 Double Glazing Co Ltd, 106 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Van Foods Ltd, 88 Chessington Road, Epsom, Surrey, KT19 9UR",
    "Welhams, 90 Chessington Road, Epsom, Surrey, KT19 9UR",
    "West Ewell Takeaway Ltd, 100 Chessington Road, Epsom, Surrey, KT19 9UR",
    "West Ewell Takeaway, West Ewell, Epsom, Surrey, KT19 9UR",
    "William Hill Bookmakers, 94 Chessington Road, Epsom, Surrey, KT19 9UR"
  ],
}